### PR TITLE
Test-palindrome-checker

### PR DESCRIPTION
**Pull request by FarwaMuhibZada**
# Palindrome_Checker 🚀

-  A  Palindrome Checker is used to check if the word or phrase that can be read the same way forwards and backwards, ignoring punctuation, case, and spacing.
-  take input from users then check multiple conditions
-   if the sentence or phrase match the condition it will show an Output and say that the sentence are palindrome
-  if it not match the condition it will show an Output and say that the sentence are  not palindrome.
-  it has the functionality that display an alert box when you submit the empty input.
-  it has a simple and perfect User Interface.
- complete all the freeCodeCamp requirements 
- pass all the check in freeCodeCamp

**Demo**
life demo link  (https://farwamuhibzada.github.io/Palindrome_Checker/)

Capture

### CODE REVIEW

**Comment by humuyar** [comment]
hi@FarwaMuhibZada Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!! bravo🥳

**Comment by humuyar** [comment]
hi@FarwaMuhibZada
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!
bravo🥳
Status Approved 👍  Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file

**Comment by FarwaMuhibZada** [comment]
> hi@FarwaMuhibZada Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!! bravo🥳 Status Approved 👍 Great Design Implemented ✔️ Created a professional Repo (You created a repository with your project name) ✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch) ✔️ Commit messages are meaningful ✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code) ✔️ No linter errors (All linters checks have been passed 🟢) ✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review) ✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request) ✔️Your code is clean ✔️Your repo has a professional README.md file

hello@humuyar!
 thanks for your reviwe and feedback .

**Review by ahzamir — APPROVED** [review]
### Hi @FarwaMuhibZada 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
- Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by FarwaMuhibZada** [comment]
@ahzamir thanks for your feedback and review.

**Pull request merged**
